apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-web
  name: app-web
spec:
  ports:
  - port: 8800
    protocol: TCP
    targetPort: 80
  selector:
    app: app-web
  type: NodePort
status:
  loadBalancer: {}
