apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-db
  name: app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-db
    spec:
      containers:
      - image: docker.io/mysql:5.7
        name: mysql
        resources: {}
status: {}
